### ISSUE TITLE
Players unexpectedly respawn on top of bedrock in NETHER type worlds.

### ISSUE THREAD

**Issue by jgilmore** [Multiverse/Multiverse-Core#1164]
This bug consistently results in players who die in a NETHER type world being respawned in a NETHER world on TOP of the bedrock ceiling.

To reproduce:
  Install multiverse-core and multiverse-netherportals.
  create two worlds, one called "world" and one called "world_nether"
    (These are implicitly linked together by multiverse-netherportals)
  go to "world", create a netherportal, and step through it.
  die, and then respawn.
  Player will find themselves on top of the nether world.

What's happening here is that it's not valid to have a spawn point in a NETHER type world, or to have a default spawn in a THE_END type world (though players CAN sleep in a THE_END type world). This setting will result in players ending up in invalid locations (over the void, or on top of the world) requiring intervention from a server admin to fix.

The work-around requires admins to manually set the respawnWorld value when creating a NETHER or THE_END type world.

It should also be possible to create the same results without multiverse-netherportals, but the "correct" behavior is harder to guess at in that instance.

Suggested solutions: There's two different ways to fix this. First, to prevent this from happening, checks could be added at several points as follows:

When a world of type NETHER or THE_END is created/imported, set the "respawnWorld" property to the linked NORMAL world, if it exists, otherwise set it to the default NORMAL world.

When a NORMAL world is created/imported, check and see if NETHER or THE_END worlds with the appropriate name exist, and link if possible.

When a "link" is established directly via the multiverse-netherportals command "/mvnp link", respawnWorld should be implicitly set.

Note that this approach would still result in unexpected behavior if a admin sets the netherportal link up manually via config files. That may or may not be acceptable.

The other, and arguably more correct way, is to leave the respawnWorld value BLANK, and attempt to guess at respawn time which world players should respawn in based the existence of worlds, respawn points set, and respawnWorld values, as they exist at that time.

**Comment by TWSSYesterday** [comment]
Cannot replicate, a lot of bugs have been fixed since the issue was posted.

**Comment by PsychoLynx** [comment]
Problem still persists, but can be circumvented by the above solution.
