### ISSUE TITLE
Nether Portal sometimes fails and causes warp to end

### ISSUE THREAD

**Issue by Matti-Koopa** [Multiverse/Multiverse-Core#1576]
I have 2 worlds set up in Multiverse. Each world has a nether and an end - so I have a total of 6 worlds.
I also installed Multiverse Nether Portals to make the nether and the end work as expected.
But on my second world the nether fails randomly. A player walks into it and sometimes he gets teleported to the end instead. When that happens, the normal portal animation doesn't play fully and the teleport seems to happen more quickly. It also happens way more often in creative mode then in survival mode. But the fact that it does happen in survival mode is a huge problem as it instantly kills the player in the end usually.
At the same time it happens the following exception get's written into the log file:

[02:37:30] [Server thread/ERROR]: Could not pass event PlayerPortalEvent to Multiverse-Core v2.5-bUNKNOWN
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-1.8.5.jar:git-Spigot-17fce80-25de1e6]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.8.5.jar:git-Spigot-17fce80-25de1e6]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.8.5.jar:git-Spigot-17fce80-25de1e6]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.8.5.jar:git-Spigot-17fce80-25de1e6]
	at net.minecraft.server.v1_8_R3.PlayerList.changeDimension(PlayerList.java:666) [spigot-1.8.5.jar:git-Spigot-17fce80-25de1e6]
	at net.minecraft.server.v1_8_R3.EntityPlayer.c(EntityPlayer.java:536) [spigot-1.8.5.jar:git-Spigot-17fce80-25de1e6]
	at net.minecraft.server.v1_8_R3.Entity.K(Entity.java:279) [spigot-1.8.5.jar:git-Spigot-17fce80-25de1e6]
	at net.minecraft.server.v1_8_R3.EntityLiving.K(EntityLiving.java:169) [spigot-1.8.5.jar:git-Spigot-17fce80-25de1e6]
	at net.minecraft.server.v1_8_R3.Entity.t_(Entity.java:246) [spigot-1.8.5.jar:git-Spigot-17fce80-25de1e6]
	at net.minecraft.server.v1_8_R3.EntityLiving.t_(EntityLiving.java:1447) [spigot-1.8.5.jar:git-Spigot-17fce80-25de1e6]
	at net.minecraft.server.v1_8_R3.EntityHuman.t_(EntityHuman.java:173) [spigot-1.8.5.jar:git-Spigot-17fce80-25de1e6]
	at net.minecraft.server.v1_8_R3.EntityPlayer.l(EntityPlayer.java:285) [spigot-1.8.5.jar:git-Spigot-17fce80-25de1e6]
	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:381) [spigot-1.8.5.jar:git-Spigot-17fce80-25de1e6]
	at net.minecraft.server.v1_8_R3.PacketPlayInFlying.a(SourceFile:126) [spigot-1.8.5.jar:git-Spigot-17fce80-25de1e6]
	at net.minecraft.server.v1_8_R3.PacketPlayInFlying$PacketPlayInPositionLook.a(SourceFile:18) [spigot-1.8.5.jar:git-Spigot-17fce80-25de1e6]
	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.8.5.jar:git-Spigot-17fce80-25de1e6]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_40]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_40]
	at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:60) [spigot-1.8.5.jar:git-Spigot-17fce80-25de1e6]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:718) [spigot-1.8.5.jar:git-Spigot-17fce80-25de1e6]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:368) [spigot-1.8.5.jar:git-Spigot-17fce80-25de1e6]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:657) [spigot-1.8.5.jar:git-Spigot-17fce80-25de1e6]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:560) [spigot-1.8.5.jar:git-Spigot-17fce80-25de1e6]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_40]
Caused by: java.lang.IllegalArgumentException: Cannot use location with null world!
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:125) ~[spigot-1.8.5.jar:git-Spigot-17fce80-25de1e6]
	at org.bukkit.event.player.PlayerMoveEvent.validateLocation(PlayerMoveEvent.java:91) ~[spigot-1.8.5.jar:git-Spigot-17fce80-25de1e6]
	at org.bukkit.event.player.PlayerMoveEvent.setFrom(PlayerMoveEvent.java:67) ~[spigot-1.8.5.jar:git-Spigot-17fce80-25de1e6]
	at com.onarandombox.MultiverseCore.listeners.MVPlayerListener.playerPortalCheck(MVPlayerListener.java:260) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor17.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_40]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_40]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.8.5.jar:git-Spigot-17fce80-25de1e6]
	... 23 more

I'm using 1.8.5 Spigot. I have no non-Multiverse plugins installed - the server is otherwise just vanilla.
I even tried building Multiverse and Multiverse Nether Portals myself to get the latest version using git - but the same error keeps happening.

**Comment by TWSSYesterday** [comment]
You'll need to edit the repo information for it to build, we're missing craftbukkit jar which is why the latest build failed. The latest on the Jenkins and Bukkit Dev should be working fine... Is there an error upon startup?

**Comment by Matti-Koopa** [comment]
I grabbed the latest builds from Jenkins (9 months and 19 days ago) for Core, NetherPortals and Portals. The error still persists.

Here is the complete server log from my attempt just now:
http://pastebin.com/6yJcPfD5

**Comment by TWSSYesterday** [comment]
Ok, I know someone apparently fixed this issue by rebooting a lot of times but I'd rather find a solution.
It seems to be versions older than 1.8.3

**Comment by Matti-Koopa** [comment]
But I'm using Spigot 1.8.5...
________________________________
Von: Liam<mailto:notifications@github.com>
Gesendet: ‎07.‎06.‎2015 14:32
An: Multiverse/Multiverse-Core<mailto:Multiverse-Core@noreply.github.com>
Cc: Matti-Koopa<mailto:matti_koopa@msn.com>
Betreff: Re: [Multiverse-Core] Nether Portal sometimes fails and causes warp to end (#1576)

Ok, I know someone apparently fixed this issue by rebooting a lot of times but I'd rather find a solution.
It seems to be versions older than 1.8.3

---

**Comment by TWSSYesterday** [comment]
Newer than*, sorry my mistake.

**Comment by TWSSYesterday** [comment]
It's a server jar issue, latest Spigot 1.8.7 works

**Comment by Matti-Koopa** [comment]
Upgraded to 1.8.7 and can't reproduce the bug anymore after I tested a few times.
Thank you.
